from pydantic import BaseModel, Field
from typing import Optional
from brainstem.utils.time import utc_now
class AssetRecord(BaseModel):
    asset_id:str; name:str; category:str='software_project'; owner_reported:str='Kindred Jermaine Cox'; legal_owner:str=''; related_entity:str=''; source:str='manual'; description:str=''; evidence_level:int=1; audit_status:str='founder_reported'; evidence_refs:list[str]=Field(default_factory=list); value_estimate_usd:Optional[float]=None; tax_relevance:str='review_needed'; risk_flags:list[str]=Field(default_factory=list); notes:str=''; created_at:str=Field(default_factory=utc_now); updated_at:str=Field(default_factory=utc_now); record_hash:str=''
class EntityRecord(BaseModel):
    entity_id:str; legal_name:str; trade_names:list[str]=Field(default_factory=list); jurisdiction:str=''; entity_type:str=''; status:str='evidence_needed'; EIN_last4:Optional[str]=None; full_EIN_known:bool=False; founder_role:str='founder'; owner_reported:str='Kindred Jermaine Cox'; public_record_url:Optional[str]=None; evidence_level:int=1; tax_relevance:str='professional_review_needed'; bank_accounts_count:Optional[int]=None; payment_processors:list[str]=Field(default_factory=list); risk_flags:list[str]=Field(default_factory=list); next_required_evidence:str='professional/legal record review'; created_at:str=Field(default_factory=utc_now); record_hash:str=''
class RevenueRecord(BaseModel):
    revenue_id:str; source_name:str; source_type:str='manual_import'; related_entity:str=''; related_product:str=''; processor:str=''; amount:float=0.0; currency:str='USD'; transaction_date:str=''; evidence_type:str='csv_import'; evidence_ref:str=''; is_mock:bool=False; tax_year:int=0; category:str='revenue'; reconciled:bool=False; risk_flags:list[str]=Field(default_factory=lambda:['professional_review_needed']); record_hash:str=''
class AuditSession(BaseModel):
    session_id:str; founder:str='Kindred Jermaine Cox'; purpose:str; started_at:str=Field(default_factory=utc_now); status:str='evidence_needed'; sources_requested:list[str]=Field(default_factory=list); sources_completed:list[str]=Field(default_factory=list); records_created:int=0; missing_private_records:list[str]=Field(default_factory=list); risk_flags:list[str]=Field(default_factory=list); next_actions:list[str]=Field(default_factory=lambda:['attach evidence','professional review']); session_hash:str=''
